# Generated by Django 4.1.5 on 2023-02-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/products/', null=True, upload_to='static/products/'),
        ),
    ]
