# Generated by Django 4.1.5 on 2023-02-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0004_cartitemsnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='image',
            field=models.ImageField(blank=True, default='static/products/', null=True, upload_to='static/products/'),
        ),
    ]
