# Generated by Django 4.1.5 on 2023-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0006_alter_singleproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproduct',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
